variable "zone" {}
variable "folder_id" {}
variable "cloud_id" {}
variable "sa_id" {}
variable "image_id" {}
variable "subnet_id" {}
variable "network_id" {}
variable "ssh_keys" {}
variable "user_data" {}
variable "name" {}
variable "hostname" {}
variable "priv_key" {}
variable "ssh_port" {}
variable "role" {}